// Code generated by goagen v1.3.0, DO NOT EDIT.
//
// API "celler": Application User Types
//
// Command:
// $ goagen
// --design=github.com/ReSTARTR/goa-gorm-sample/design
// --out=$(GOPATH)/src/github.com/ReSTARTR/goa-gorm-sample
// --version=v1.3.0

package client
